services:

  db:
    container_name: snippetbox-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /volume-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: password
